### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [breda/zsh-ssh-quickconnect#1]
This is mentioned in https://github.com/unixorn/awesome-zsh-plugins/pull/1713 but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by breda** [comment]
@unixorn I had a license locally but totally forgot to push. Done now, thank you!

**Comment by unixorn** [comment]
NP, I can't count the times I forgot to add a file, or to push again after adding commits.
